apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keymaker-dev # {production/stage/qa}
  name: cmis-service  # Specify the deployment name.
spec:
  replicas: 1 # Specify your replica - how many instances you want from that deployment.
  selector:
    matchLabels:
      app: cmis-service  # Specify the app label. It is optional but it is a good practice.
  template:
    metadata:
      labels:
        app: cmis-service # Specify app label. It is optional but it is a good practice.
        version: v1 # Specify your version.
    spec:
      containers:
      - name: cmis-service
        image: solviadscom/cmis-service:0.0.9
        ports:
        - containerPort: 9091
      imagePullSecrets:
      - name: ardas-docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cmis-service
  namespace: keymaker-dev
  labels:
    app: cmis-service
spec:
  ports:
    - name: http
      port: 9091
  selector:
    app: cmis-service
---

