apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: doehler-test # {production/stage/qa}
  name: kyma-cmis-service # Specify the deployment name.
spec:
  replicas: 1 # Specify your replica - how many instances you want from that deployment.
  selector:
    matchLabels:
      app: kyma-cmis-service # Specify the app label. It is optional but it is a good practice.
  template:
    metadata:
      labels:
        app: kyma-cmis-service # Specify app label. It is optional but it is a good practice.
        version: v1 # Specify your version.
    spec:
      containers:
        - name: kyma-cmis-service # Specify a meaningful container name.
          image: index.docker.io/solviadscom/doehler-kyma-scp-rfqservice4soapqa:latest # Specify your image {registry FQN/your-username/your-space/image-name:image-version}.
          ports:
            - containerPort: 9091 # Specify the port to your image.
      imagePullSecrets:
        - name: docker-registry-secret # Specify the same Secret name you generated in the previous step for this Namespace.
---
apiVersion: v1
kind: Service
metadata:
  name: doehler-kyma-scp-rfqservice4soapqa
  namespace: doehler-test
  labels:
    app: doehler-kyma-scp-rfqservice4soapqa
spec:
  ports:
    - name: http
      port: 8074
  selector:
    app: doehler-kyma-scp-rfqservice4soapqa
---